version: 0.2

phases:
  install:
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - mkdir src
      - ls -al
      - cd ./src
      - ls -al
      - mkdir github.com
      - ls -al
      - cd github.com
      - ls -al
      - git clone https://github.com/qowns8/ideaweb
      - dep ensure
  build:
    commands:
      - go build
artifacts:
  files:
    - ideaweb