version: 0.2

phases:
  install:
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - mkdir src
      - cd ./src
      - mkdir github.com
      - cd github.com
      - mkdir qowns8
      - cd qowns8
      - git clone https://github.com/qowns8/ideaweb
      - cd ideaweb
      - dep ensure
  build:
    commands:
      - go build -o bin/application main.go
artifacts:
  files:
    - src/github.com/qowns8/ideaweb/bin/application
  discard-paths: yes